version: '3.8'

volumes:
  vol_vaultwarden_prod:
    driver: local
    name: vol_vaultwarden_prod
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_IP_ADDRESS},nolock,rw,soft,nfsvers=4"
      device: ":${NFS_PATH_DOCKER_VOLUMES}/vaultwarden"

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    volumes:
      - type: volume
        source: vol_vaultwarden_prod
        target: /data
        volume:
          nocopy: true    
    ports:
      - ${PORT_VAULTWARDEN}:80
    environment:
      - TZ="${TIMEZONE}"
      - PUID=${PUID}
      - PGID=${PGID}
    tmpfs:
      - /run
      - /tmp
      - /var/cache
