version: '3.3'

volumes:
  vol_media_youtube:
    driver: local
    name: vol_media_youtube
    driver_opts:
      type: cifs
      device: "${HOST_PATH_YOUTUBE}"
      o: "username=${NAS_USERNAME},password=${NAS_PASSWORD},uid=${PUID},gid=${PGID}"
services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    hostname: metube
    restart: unless-stopped
    volumes:
      - type: volume
        source: vol_media_youtube
        target: /downloads
    ports:
      - ${PORT_METUBE}:8081
    environment:
      - TZ="${TIMEZONE}"
      - PUID=${PUID}
      - PGID=${PGID}
    tmpfs:
      - /run
      - /tmp
      - /var/cache
