version: '3.3'

volumes:
  # NFS Volumes to store data from the containers
  vol_homer_rui:
    driver: local
    name: vol_homer_rui
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_IP_ADDRESS},nolock,rw,soft,nfsvers=4"
      device: ":${NFS_PATH_DOCKER_VOLUMES}/homer_rui"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer_rui
    hostname: homer_rui
    user: ${PUID}:${PGID}
    restart: unless-stopped
    volumes:
      - type: volume
        source: vol_homer_rui
        target: /www/assets
        volume:
          nocopy: true
    ports:
      - ${PORT_HOMER}:8080
    environment:
      - TZ="${TIMEZONE}"
      - INIT_ASSETS=0
    # Write all logs to the ram.
    # The data stored in the specified directory will be stored in the host system's memory (RAM), and it will be cleared when the container stops
    tmpfs:
      - /run
      - /tmp
      - /var/cache
